### ISSUE TITLE
Fails with UTC offset > 0

### ISSUE THREAD

**Issue by ghost** [Jehops/zap#1]
My time zone is CEST (UTC+2), and running `zap 1d thor/home/tobias` fails with
`cannot create snapshot 'thor/home/tobias@ZAP_2016-04-01T12:54:00+0200--1d': invalid character '+' in name`

**Comment by Jehops** [comment]
Thanks for catching this.  I've committed an update, which replaces the '+' with 'p' since ZFS doesn't allow '+' in component names.
