### ISSUE TITLE
unable to replicate on FreeBSD 11.1

### ISSUE THREAD

**Issue by mccaslin** [Jehops/zap#14]
Attempting zap rep generates an error:  invalid option 'c'

apparently the version of zfs in 11.1 doesn't support the 'c' option for zfs send.  Is there somewhere I can customize the send options?

**Comment by Jehops** [comment]
Hi,

There isn't a flag to toggle compression when replicating. A quick hack until you can upgrade is to just remove the `-c` flag from `zfs send` in the script.  I see these lines that would need to be edited:

```
320:    if zfs send -Lcep "$lsnap" | zfs recv -Fu $v_opt -d "$rloc"; then
344:    if zfs send -Lcep "$lsnap" | \
396:        if zfs send -Lce $i "$sp" "$lsnap" | zfs recv -du $F_opt $v_opt \
410:        if zfs send -Lce $i "$sp" "$lsnap" | \
```

Icymi, [FreeBSD 11.1 went EOL in September 2018](https://www.freebsd.org/security/unsupported.html).

**Comment by mccaslin** [comment]
Thank you very much for the help! You gave this much more of a response
than it deserved.

I should have paid more attention before opening an issue.

Since opening it I realized I could just search and replace the arguments
in the script.  All is working fine now.  I had indeed missed that 11.1 was
EOL. I will be upgrading ASAP.

Thank you for building such a useful,  well thought out tool.
