### ISSUE TITLE
-Lce does not work with zfs on Debian 9

### ISSUE THREAD

**Issue by tomatt** [Jehops/zap#15]
I get an error message while replicating that the -c is not supported.
I have version 0.6.5.9-5 of zfs which comes with Debian 9.

**Comment by Jehops** [comment]
Thanks for reporting.  I'll try and find a Debian 9 system to test and work around the problem, but it might take me some time.

**Comment by Jehops** [comment]
Sorry for the very long delay.  I received an email report about a similar problem on NetBSD, which reminded me of your report.  I just pushed some changes to the `netbsd_fixes` branch, which adds a new option, `-C`.  When that option is supplied `zfs send` will be run without the `-c` flag.  Does this fix your issue?

**Comment by tomatt** [comment]
I will give it a try! Thanks a lot for the fix.

**Comment by Jehops** [comment]
I merged this fix to master.  I will close this, but please re-open if you still have a problem.
