### ISSUE TITLE
Problems with dataset names with spaces

### ISSUE THREAD

**Issue by ghost** [Jehops/zap#2]
Hi,

got a chance to try your new fixes and all seems to work ok AFAICT. I however noticed two small problems:

Creating snapshots of datsets that have spaces in their name works fine, but destroying them does not:

```
zfs create "thinkpad/blabla bla"
zap 1d "thinkpad/blabla bla"
zap -d
```

fails with

```
cannot open 'bla@ZAP_2016-04-06T12:31:54p0200--1d': invalid character '@' in pool name
```

The fix seems to be easy:

``` diff
diff --git a/zap b/zap
index 5f3aebe..71da9a9 100755
--- a/zap
+++ b/zap
@@ -119,7 +119,7 @@ create () {

 destroy () {
     now_ts=$(date '+%s')
-    for i in $(zfs list -H -t snap -o name); do
+    zfs list -H -t snap -o name | while read i; do
         if echo "$i" | cut -f1 -d'/' | xargs zpool status \
                 | grep -q "DEGRADED\|FAULTED\|OFFLINE\|REMOVED\|UNAVAIL"; then
             warn "zap skipped destroying $i because of pool state!"
```

Then there are problems with destroying snapshots of the root dataset. `zap -d` returns:

```
cannot open 'thinkpad@ZAP_2016-04-06T08:40:00p0200--3d': invalid character '@' in pool name
```

It's obviously a problem with `cut -f1 -d'/'`, but I don't know how to solve this in a good way.

P.S.: I have a small zap companion script that adds support for ZFS properties: https://gist.github.com/t6/6a0910d85e49423657101c57c892ca8c

**Comment by Jehops** [comment]
Thanks!  The latest commit should fix these issues. I will set aside some time to have a closer look at your companion script.

**Comment by ghost** [comment]
Thanks, but there is another problem with renaming snapshots :disappointed:: 

```
cannot open 'thinkpad/blabla': dataset does not exist
```

Example:

``` bash
r="thinkpad/blabla bla 42   0"
echo "${r%%[[:space:]]*}"
# => thinkpad/blabla
echo "${r##*[[:space:]]}"
# => 42 0
```

**Comment by Jehops** [comment]
I think this should do it.

**Comment by ghost** [comment]
Yep, that fixes it. Thanks!
