### ISSUE TITLE
Add ZAP_FILTER_REMOTE

### ISSUE THREAD

**Issue by sevmonster** [Jehops/zap#20]
I was following along with #16 and one concern I have is using the same command on both the local and remote host. I like the idea of adding to the pipeline (and I will certainly be using `mbuffer` with it because my performance is terrible over the wire otherwise) but what if the local and remote filters should not or cannot be the same? I think splitting the remote filter into `ZAP_FILTER_REMOTE` would be the best option, and a value of `-` or something would retain current functionality where `ZAP_FILTER` is used for both local and remote, without having to explicitly copy to the other variable yourself.

For example:
- Use different `mbuffer` buffer sizes on the local and remote machines
- Compress before sending: `ZAP_FILTER='lz4 -c -' ZAP_FILTER_REMOTE='lz4 -cd -' zap rep`
- Show status on local machine only: `ZAP_FILTER=pv zap rep`  
(I imagine `pv` on remote over SSH would not be an issue since a tty is still being allocated, but maybe it isn't available on remote, or I could be wrong and it would cause a problem... I do not use `pv` myself so I have no idea.)

**Comment by Jehops** [comment]
Thanks.  I agree that this is a good idea.  I will try to get it implemented soon.

**Comment by Jehops** [comment]
Could you test the implementation above to see if it meets your needs?

**Comment by sevmonster** [comment]
I'm sorry, there are other things keeping me from trying this out. However, the commit looks good, and I can assume that it will work. If you would still like me to test in my environment it may be a bit.

**Comment by sevmonster** [comment]
It looks like there is an extra `else` at line [488](https://github.com/Jehops/zap/commit/86ac36bf7377e7af0a4596594bab77695f9e87d8#diff-b4c5ae2ae961fe88d12821bdf945b15482ef021703e1f900ccbe1a27f22df07fR488)

**Comment by Jehops** [comment]
Fixed.  Thanks.

**Comment by sevmonster** [comment]
Testing this on a large dataset now with `mbuffer`, working great. Example from a prior test:
```
%sev@host1: sudo zfs set zap:snap=on zap:rep=zap@host2:pool/backup pool/dataset
%sev@host1: sudo -u zap zap snap 1d
%sev@host1: sudo -u zap ZAP_FILTER="mbuffer -q -s 128k -m 1G" ZAP_FILTER_REMOTE="mbuffer -q -s 128k -m 512M" zap rep -v | tail +5
Replicating host1...
No remote snapshots found. Sending full stream.
zfs send -Lep -c -w pool/dataset@ZAP_host1_2021-07-26T01:41:44-0500--1d | mbuffer -q -s 128k -m 1G | ssh zap@host2 sh -c 'mbuffer -q -s 128k -m 512M | zfs recv -Fu -v -d pool/backup/dataset'
receiving full stream of pool/dataset@ZAP_host1_2021-07-26T01:41:44-0500--1d into pool/backup/dataset@ZAP_host1_2021-07-26T01:41:44-0500--1d
received 50.9K stream in 1 seconds (50.9K/sec)
zfs bookmark pool/dataset@ZAP_host1_2021-07-26T01:41:44-0500--1d pool/dataset#ZAP_host1_2021-07-26T01:41:44-0500--1d
zfs set zap:snap=off for zap@host2:pool/backup/dataset
zfs set zap:rep=off for zap@host2:pool/backup/dataset
Set canmount=noauto for zap@host2:pool/backup/dataset
```
