### ISSUE TITLE
Do not use `/dev/stdout` or `/dev/stderr` on Linux

### ISSUE THREAD

**Issue by sevmonster** [Jehops/zap#21]
`/dev/stdout` and `/dev/stderr` are handled on modern Linux by linking to the file descriptor in the proc filesystem at `/proc/self/fd/{1,2}`, which usually links to your psuedoterminal slave... However, upon switching user with `su` or `sudo` (and I imagine `doas`), not all systems are configured to update permissions to allow the user to write to it. I've read that ConsoleKit might address this, but in my environment (Alpine Linux, Busybox `mdev` or `eudev`, Busybox `login`, OpenRC) it does not happen:
```
%sev@host: zap -v
WARN: zap has not be sufficiently tested on Linux.
      Feedback and patches are welcome.

0.8.1
%sev@host: sudo -u zfs zap -v
zap: line 172: can't create /dev/stderr: Permission denied
zap: line 630: can't create /dev/stderr: Permission denied
%sev@host/1: sudo -u zfs ls -l /dev/stderr
lrwxrwxrwx    1 root     root            15 Jun 28 10:19 /dev/stderr -> /proc/self/fd/2
%sev@host: sudo -u zfs ls -l /proc/self/fd/2
lrwx------    1 zfs      nogroup         64 Jun 30 11:50 /proc/self/fd/2 -> /dev/pts/0
%sev@host: sudo -u zfs ls -l /dev/pts/0
crw--w----    1 sev      tty       136,   0 Jun 30 11:51 /dev/pts/0
```
(FYI: `proc` file descriptor links are actually duplicating the requested descriptor in the kernel when they are opened, they are not real links)

To fix this, POSIX descriptor redirects should be used instead:
```diff --git a/zap b/zap
index e8253e2..e205a66 100755
--- a/zap
+++ b/zap
@@ -169,7 +169,7 @@ val_dest () {
 }

 warn () {
-  echo "WARN: $*" > /dev/stderr
+  echo "WARN: $*" >&2
 }

 # ==============================================================================
@@ -627,6 +627,6 @@ case $1 in
   snap|snapshot) shift; snap_parse "$@" ;;
   rep|replicate) shift; rep_parse  "$@" ;;
   destroy)       shift; destroy    "$@" ;;
-  -v|-version|--version) echo "$version" > /dev/stderr ;;
+  -v|-version|--version) echo "$version" >&2 ;;
   *)             usage "${0##*/}: missing or unknown subcommand -- $1"; exit 1 ;;
 esac
```
```
%sev@host: sudo -u zfs zap -v
WARN: zap has not be sufficiently tested on Linux.
      Feedback and patches are welcome.

0.8.1
```
Further reading: https://unix.stackexchange.com/questions/38538

I do not have a FreeBSD machine on hand to test with. On FreeBSD, `/dev/stdout` and `/dev/stderr` link to `/dev/fd/{1,2}`.

**Comment by Jehops** [comment]
Looks good.  Committed (with you as author) in 5fef3d0.

Thanks.
