### ISSUE TITLE
Busybox `date` cannot parse snapshot timestamps

### ISSUE THREAD

**Issue by sevmonster** [Jehops/zap#22]
## Problem
Snapshot timestamps are generated using use the `strftime` format `%Y-%m-%dT%H:%M:%S%z` with `date`. No problems yet, Busybox `date` uses the underlying C library's `strftime`, and all popular libraries can parse `%z` when building dates. The problems start when zap's `ss_ts` function tries to convert the snapshot timestamp back to seconds-since-epoch for processing. This does not work when using Busybox `date`:
```
#output of zap with `set -x`
%sev@host: zap rep -v
...
+ ss_ts 2021-07-24T17:38:15-0500
+ echo 2021-07-24T17:38:15-0500
+ sed 's/T/ /'
+ gdate='2021-07-24 17:38:15-0500'
+ date '-d2021-07-24 17:38:15-0500' '+%s'
date: invalid date '2021-07-24T17:38:15-0500'
```
The reason for this is because Busybox `date -d` does not include the timezone in any of its recognized list of formats:
```
%sev@host: date --help
...
Recognized TIME formats:
        @seconds_since_1970
        hh:mm[:ss]
        [YYYY.]MM.DD-hh:mm[:ss]
        YYYY-MM-DD hh:mm[:ss]
        [[[[[YY]YY]MM]DD]hh]mm[.ss]
        'date TIME' form accepts MMDDhhmm[[YY]YY][.ss] instead
```
It doesn't parse the timezone by default because Busybox `date` uses the [underlying libc `strptime`](https://git.busybox.net/busybox/tree/coreutils/date.c#n276), and according to the POSIX specification, `strptime` does not support parsing timezones or offsets (see *IEEE Std 1003.1-2017 Issue 7, Vol. 2, Chap. 3, strptime(), pg. 2065*).

## Solutions
In order to be compliant with POSIX, the timezone offset should be stripped from the timestamp, both independently converted to seconds, and summed. The stripped timestamp can use `date` while the offset should be calculated manually.

There is a shortcut that can be taken if the underlying C library supports `%z` in `strptime`, for example [glibc](https://sourceware.org/git/?p=glibc.git;a=blob;f=time/strptime_l.c;h=02c5d63c798f9c136600ccc4d508a574083f1048;hb=HEAD#l776) and [EGLIBC](http://www.eglibc.org/cgi-bin/viewvc.cgi/trunk/libc/time/strptime_l.c?view=markup). Busybox `date` accepts the non-standard parameter `-D` which allows you to specify the format string to parse the date with. Therefor, this issue can be bypassed in such a circumstance by specifying the timezone offset `%z` in a format string to `date -D`. Other C libraries that don't support `%z` like [musl libc](https://git.musl-libc.org/cgit/musl/tree/src/time/strptime.c) will still encounter an error. On uClibc, [`%z` is no-op](https://git.busybox.net/uClibc/tree/libc/misc/time/time.c#n1681).

## Caveats
According to the POSIX specification, `strftime` `%z` should always be constructed following the ISO 8601:2004 standard format of `[+-]hhmm`, so any `date` implementation that claims compatibility with POSIX `strftime` or `date` should use this format. Based on my research I cannot find any instance where this is incorrect, aside from older versions of coreutils (I do not know which). When constructing a date from a format string using coreutils `date`, older versions defaulted to including `:` for `%z` (`[+-]hh:mm`). In the current version of coreutils this has since been removed from `%z` and is now accomplished using `%:z`. In order to maintain backwards compatibility with snapshots made with older coreutils, this format should be accepted.

**Comment by sevmonster** [comment]
PR #23

I tested on Alpine Linux edge with both Busybox `date` and coreutils `date`, both resulted in the correct time:
```
%sev@host: source zap
...
%sev@host: set -x
%sev@host: ss_ts 2021-07-25T03:51:29-0500
+ '[' 0 -eq 0 ]
+ '[' 1 -eq 0 ]
+ echo 2021-07-25T03:51:29-0500
+ grep -Eo '[+-]\d\d:?\d\d$'
+ offset=-0500
+ sign=-
+ h=05
+ '[' 0 '=' : ]
+ m=00
+ '[' 00 -gt 59 ]
+ echo 2021-07-25T03:51:29
+ sed 's/T/ /'
+ date '-ud2021-07-25 03:51:29' '+%s'
+ sec=1627185089
+ '[' 0 -ne 0 ]
+ echo '1627185089 - ((05 * 60 + 00) * -60)'
+ bc
1627203089
%sev@host: sudo apk add coreutils
...
%sev@host: ss_ts 2021-07-25T03:51:29-0500
+ '[' 1 -eq 0 ]
+ echo 2021-07-25T03:51:29-0500
+ sed 's/T/ /'
+ date '-d2021-07-25 03:51:29-0500' '+%s'
1627203089
```

I do not have a machine with glibc on hand, but I am entriely certain that path should work.

**Comment by Jehops** [comment]
Thanks for this and thanks for the thorough explanation.  Merged.
