### ISSUE TITLE
How one can specify custom ssh port?

### ISSUE THREAD

**Issue by priyadarshan** [Jehops/zap#5]
On two servers I am setting up I need to use a custom ssh port, `-p 7000`.

Is it possible to specify a custom ssh port wit `zap`?

**Comment by Jehops** [comment]
I add something like this to ~/.ssh/config.
```
Host myhost1
Port 7000

Host myhost2
Port 7000
```

**Comment by priyadarshan** [comment]
Thank you, that works.

Thank you for `zap`!
