### ISSUE TITLE
-d option has no effect when taking a snapshot in 0.6.9

### ISSUE THREAD

**Issue by Partmedia** [Jehops/zap#6]
When I run:
```
$ sudo zap snap -d 1w        
WARN: DID NOT snapshot pool/home because of pool state!
```
I hardwired pool_ok () to always return 0, and the snapshot takes place normally. I suspect something is wrong with the current implementation of pool_ok().

**Comment by Jehops** [comment]
Could you show the output of `zpool status` for the pool?

**Comment by Partmedia** [comment]
````
  pool: foxtrot-pool
 state: DEGRADED
status: One or more devices could not be opened.  Sufficient replicas exist for
	the pool to continue functioning in a degraded state.
action: Attach the missing device and online it using 'zpool online'.
   see: http://illumos.org/msg/ZFS-8000-2Q
  scan: resilvered 3.43G in 0h7m with 0 errors on Fri May 12 21:43:29 2017
config:

	NAME                      STATE     READ WRITE CKSUM
	foxtrot-pool              DEGRADED     0     0     0
	  mirror-0                DEGRADED     0     0     0
	    ada0p4.eli            ONLINE       0     0     0
	    10414615541754761793  UNAVAIL      0     0     0  was /dev/da0p1.eli

errors: No known data errors
````

**Comment by Jehops** [comment]
The "UNAVAIL" for /dev/da0p1.eli is being matched by the grep at the end of pool_ok().  That grep is meant to match against the pool state, not that state of individual devices.

Thanks for reporting this.  I'll come up with a fix soon.

**Comment by Jehops** [comment]
I just pushed a fix and will soon roll a new release.

Your issue has made me think that the default behaviour should be changed, so that snapshots are created by default when the pool is in a DEGRADED state.  What do you think?

**Comment by Partmedia** [comment]
Thanks for the fix. I agree that the default behavior should be changed as you suggested. I don't think a degraded pool should stop snapshot creation.

**Comment by Jehops** [comment]
The default behaviour has been updated.  When you are satisfied, please close the issue and I will roll version 0.7.0.

**Comment by Partmedia** [comment]
Thanks again for the help and fixes, and for working on the zap tool!
